#
# $Id: bash_profile 1272 2009-10-15 23:42:46Z suriya $
#

#
# Suriya Subramanian on Wed Aug 13 18:48:06 CDT 2003
# Sun Mar 28 22:08:58 CST 2004
# Sat Aug 14 16:22:07 CDT 2004
#

# I am in the CS department of the University of Texas at Austin and they
# have (peculiar) way of setting up the Environmental Variables using a
# per user ~/.profile rather than a system wide file. We source that file
# first.
#
if [ -f ~/.profile ]
then
    source ~/.profile
fi

#
# Using keychain for ssh-agent and ssh keys management
#
if [ -a ~/.ssh/id_rsa ] && [ ${HOSTNAME#*.} == "cs.utexas.edu" ] && [ ${HOSTNAME:0:7} != "horatio" ]
then
    ~/bin/keychain id_rsa
    source ~/.keychain/$HOSTNAME-sh
fi

# include .bashrc if it exists

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
